version: '3.7'

services:
  bodhi-server-mainnet:
    hostname: bodhi-server-mainnet
    container_name: bodhi-server-mainnet
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/mainnet/Dockerfile
    ports:
      - 8888:8888
    environment:
      - CONTRACT_VERSION=0
      - NETWORK=mainnet
      - SSL=true
      - SSL_KEY_PATH=/root/bodhi-server/creds/nakachain.org.key
      - SSL_CERT_PATH=/root/bodhi-server/creds/nakachain.org.crt
      - LOG_LEVEL=debug
    volumes:
      - bodhi-server-mainnet:/root/bodhi-server/data
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

volumes:
  bodhi-server-mainnet:
