version: '3.7'

services:
  bodhi-server-mainnet:
    hostname: bodhi-server-mainnet
    container_name: bodhi-server-mainnet
    restart: always
    stop_signal: SIGINT
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
      args:
        NAKABASE_API_KEY: ${NAKABASE_API_KEY}
    ports:
      - 8888:8888
    environment:
      - EXPOSED_PORTS="8888"
      - NETWORK=mainnet
      - SSL=true
      - SSL_KEY_PATH=/root/creds/puti.io.key
      - SSL_CERT_PATH=/root/creds/puti.io.pem
      - LOG_LEVEL=debug
    volumes:
      - /home/ubuntu/.bodhi/mainnet:/root/data
      - /home/ubuntu/.naka/mainnet/geth.ipc:/root/.bodhi/mainnet/geth.ipc
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
