version: '3.7'

services:
  bodhi-server-testnet:
    hostname: bodhi-server-testnet
    container_name: bodhi-server-testnet
    restart: always
    stop_signal: SIGINT
    build:
      context: ../../
      dockerfile: ./docker/testnet/Dockerfile
    ports:
      - 9999:9999
    environment:
      - NETWORK=testnet
      - SSL=true
      - SSL_KEY_PATH=/root/bodhi-server/creds/nakachain.org.key
      - SSL_CERT_PATH=/root/bodhi-server/creds/nakachain.org.pem
      - LOG_LEVEL=debug
    volumes:
      - /home/ubuntu/.bodhi/testnet:/root/bodhi-server/data
      - /home/ubuntu/.naka/testnet/geth.ipc:/root/geth.ipc
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
