version: '3.7'

services:
  bodhi-server-testnet:
    hostname: bodhi-server-testnet
    container_name: bodhi-server-testnet
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/testnet/Dockerfile
    ports:
      - 9999:9999
    environment:
      - CONTRACT_VERSION=0
      - NETWORK=testnet
      - SSL=true
      - SSL_KEY_PATH=/run/secrets/nakachain.org.key
      - SSL_CERT_PATH=/run/secrets/nakachain.org.crt
      - DATA_DIR=/home/ubuntu/.bodhi/server/testnet
      - LOG_LEVEL=debug
    volumes:
      - bodhi-server-testnet:/home/ubuntu/.bodhi/server/testnet
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    secrets:
      - privkey.pem
      - fullchain.pem

secrets:
  nakachain.org.key:
    file: /etc/ssl/private/nakachain.org.key
  nakachain.org.crt:
    file: /etc/ssl/certs/nakachain.org.crt

volumes:
  bodhi-server-testnet:
