module.exports = {
  EVENT_MESSAGE: {
    WEBSOCKET_CONNECTED: 'WEBSOCKET_CONNECTED',
    WEBSOCKET_DISCONNECTED: 'WEBSOCKET_DISCONNECTED',
  },

  BLOCKCHAIN_ENV: {
    MAINNET: 'mainnet',
    TESTNET: 'testnet',
  },

  WEB3_PROVIDER: {
    IPC: 'ipc',
    WS: 'ws',
    HTTP: 'http',
  },

  EVENT_STATUS: {
    CREATED: 'CREATED',
    PRE_BETTING: 'PRE_BETTING',
    BETTING: 'BETTING',
    PRE_RESULT_SETTING: 'PRE_RESULT_SETTING',
    ORACLE_RESULT_SETTING: 'ORACLE_RESULT_SETTING',
    OPEN_RESULT_SETTING: 'OPEN_RESULT_SETTING',
    ARBITRATION: 'ARBITRATION',
    WITHDRAWING: 'WITHDRAWING',
  },

  TX_TYPE: {
    CREATE_EVENT: 'CREATE_EVENT',
    BET: 'BET',
    RESULT_SET: 'RESULT_SET',
    VOTE: 'VOTE',
    WITHDRAW: 'WITHDRAW',
  },

  TX_STATUS: {
    PENDING: 'PENDING',
    SUCCESS: 'SUCCESS',
    FAIL: 'FAIL',
  },

  ORDER_DIRECTION: {
    ASCENDING: 'ASC',
    DESCENDING: 'DESC',
  },

  INVALID_RESULT_INDEX: 255,
};
